name: Generate Datas

on:
  workflow_dispatch: # execute manually
  push:
    branches: 
      - main  
  
  schedule:
    - cron:  "0 0 * * *" 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics-full-year-calendar
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: assets/metrics.plugin.isocalendar.svg
          token: ${{ secrets.GH_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent-activity-charts
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.habits.charts.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Shanghai
          
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

      - name: account
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.classic.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          
  github-Snake:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: Platane/snk@v2.3.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          default_author: github_actions
          message: 'Generate Contribution Snake'
