name: Generate Datas

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          default_author: github_actions
          message: 'Generate Contribution Snake'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
